spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/JamyLeo/springcloudConfig/
#          uri: https://github.com/how2j/springcloudConfig/
          searchPaths: respo/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/